### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by IzzySoft** [MasterGamesMG/ELFReader#1]
As you didn't specify a license: could you please clarify which license you project falls under? The only license remark I could find in the repo here was Apache-2.0 as used by Gradle. Thanks in advance!

**Comment by MasterGamesMG** [comment]
Hello, sorry for not specifying more would be for free use among others what would be cataloged as "wtfpl".

**Comment by MasterGamesMG** [comment]
Hello, sorry for not specifying more would be cataloged as "afl-3.0".

**Comment by IzzySoft** [comment]
Wonderful! [AFL-3.0](https://spdx.org/licenses/AFL-3.0.html) is approved by OSI **and** FSF, perfect! Can you add that to your Readme, please?

Speaking of "add": I took the freedom to already add your app to my repo, it just went [live here](https://apt.izzysoft.de/fdroid/index/apk/com.mastergames.elfreader) about an hour ago. License will be fixed with the next sync tomorrow around 7 pm UTC. Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there from your Readme if you like :smiley: Updates will become available there usually within 24h of your tagging a new release and adding an APK to it.

**Comment by MasterGamesMG** [comment]
Thank you very much I put the insignia in README, and already added on the license.

**Comment by IzzySoft** [comment]
Ah, wonderful! Can you please link the badge to point to `https://apt.izzysoft.de/fdroid/index/apk/com.mastergames.elfreader` (or `https://apt.izzysoft.de/packages/com.mastergames.elfreader/` if you prefer) instead of to the graphic itself?

Meanwhile it seems I should replace the AFL-3.0 I just added in my repo by GPL-3.0 (you seem to have changed your mind unless you just picked the wrong license file: WTFPL › AFL-3.0 › GPL-3.0. So will it be "GPL-3.0-only" (as it shows now), or "GPL-3.0-or-later"? In the last case, please see the "block" following the "END OF TERMS AND CONDITIONS" in `LICENSE.md`, which then should be copied to your Readme. Your decision of course – all 3 licenses are absolutely fine, and GPL is fine with or without "later" as well :smile:

**Comment by MasterGamesMG** [comment]
I think everything would be ready, yes I in the end changed the license

**Comment by IzzySoft** [comment]
OK, thanks – then I guess we can close here (and btw: You could have kept the badge in; just when clicked it shouldn't open the image but the link to your app in my repo :wink:).

I've set the license to `GPL-3.0-only` then. If you want me to send the metadata I've set up as PR in Fastlane format so you can control how the app is presented in my repo, just let me know (for guidance, you could then use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688)). Fastlane is the de-facto standard for that.
